# Cloud Build command to load and config VHD_DETAILS from cloud store.
# @TODO Add commands to build all the tables, especially if a schema is requried.
  
steps:

# 1 REMOVE TABLE  _VHD_DETAILS
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_TARGET_DATASET}.${_VHD_DETAILS}'

# 2 CREATE TABLE: ${_VHD_DETAILS}
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'load'
  - '--project_id=${_PROJECT_ID}'
  - '--skip_leading_rows=1'
  - '--source_format=CSV'
  - '--replace=true'
  - '--autodetect=true'
  - '${_TARGET_DATASET}.${_VHD_DETAILS}'
  - '${_SOURCE_VHD_DETAILS_CSV}'

# 3 UPDATE TABLE: ${_VHD_DETAILS}
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'update'
  - '--set_label=build:build-tables-yaml'
  - '--set_label=heritage-maps:required'
  - '--expiration=0'
  - '--description=${_VHD_DETAILS_DESCR}'
  - '${_TARGET_DATASET}.${_VHD_DETAILS}'

substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  _TARGET_DATASET: YarraPlanning # PROD_DATASET - Add this in the trigger configuration

  # INPUT FILES
  _SOURCE_VHD_DETAILS_CSV: gs://yarra_planning_applications_au/yarra_vhr_20190802.csv
  
  # OUTPUT TABLES IN TARGET_DATASET
  _VHD_DETAILS: VHR_DETAILS
  
  # DECSCRIPTIONS
  _VHD_DETAILS_DESCR:  |
    TABLE - ${_VHD_DETAILS} - BUILT WITH CLOUD BUILD
    cloudbuild/build-tables.yaml. 
    LOADED FROM CSV FILE GENERATED BY SCRAPE_VHD


