substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  _SRC_DATASET: YarraPlanning
  _TARGET_DATASET: PROD_DATASET
  _RANGE_FROM_HO330: 1200

  # INPUTS TABLES
  _HERITAGE_REGISTER: HERITAGE_REGISTER_C191_WITHVHD
  _YARRA_PROPS: YARRA_PROPERTIES 
  _YARRA_OVERLAYS: YARRA_OVERLAYS
  
  # OUTPUTS
  _OVERLAYS_AVG_DATE: OVERLAYS_AVG_ESTABLISHED_DATE
  _OVERLAYS_VIEW: OVERLAYS
  _HERITAGE_PROPS_TABLE: YARRAHERITAGEMAPS_PROPERTIES
  
  # DECSCRIPTIONS
  _HERITAGE_PROPS_TABLE_DESCR:  |
    TABLE - ${_HERITAGE_PROPS_TABLE} - BUILT WITH CLOUD BUILD
    cloudbuild/build-views.yaml. 
    JOINS TABLES 
      - ${_HERITAGE_REGISTER} from ${_SRC_DATASET}
      - YARRA_PROPERTIES from ${_SRC_DATASET}
      - VHD from VHD
    ${_HERITAGE_REGISTER} has been matched to PFIs and vhdplacesId. 
    The query to create this table merges data from VHD properties and de-duplicates.
    It then merges boundary geometry from YARRA_PROPERTIES checking each of the PROPERTY_PFI rows for a geometry that contains the VHDLocation.
    It then merges boundary geometry from YARRA_PROPERTIES matching  PROPNUM if its geometry contains the VHDLocation.
    If no boundary is found, then the vhdPoint is set as the bndry.
    USES TABLES 
      - ${_HERITAGE_REGISTER} from ${_SRC_DATASET}
      - YARRA_PROPERTIES from ${_SRC_DATASET}
      - VHD from VHD table.

steps:

# 1A REMOVE TABLE  _HERITAGE_PROPS_TABLE
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_TARGET_DATASET}.${_HERITAGE_PROPS_TABLE}'

