steps:

# 1A REMOVE TABLE  _HERITAGE_PROPS_TABLE
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_TARGET_DATASET}.YARRAHERITAGEMAPS_PROPERTIES'
substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  _SRC_DATASET: YarraPlanning
  _TARGET_DATASET: YarraPlanning
  _RANGE_FROM_HO330: 30000

  # INPUTS TABLES
  _HERITAGE_REGISTER: HERITAGE_REGISTER_C191_WITHVHD
  _YARRA_PROPS: YARRA_PROPERTIES 
  _YARRA_OVERLAYS: YARRA_OVERLAYS
  
  # OUTPUTS
  _OVERLAYS_AVG_DATE: OVERLAYS_AVG_ESTABLISHED_DATE
  _OVERLAYS_VIEW: OVERLAYS
  _HERITAGE_PROPS_TABLE: YARRAHERITAGEMAPS_PROPERTIES
  
  # DECSCRIPTIONS
  _HERITAGE_PROPS_TABLE_DESCR:  short description

