steps:

# 1A REMOVE TABLE  _HERITAGE_PROPS_TABLE
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_TARGET_DATASET}.${_HERITAGE_PROPS_TABLE}'

substitutions:
  _PROJECT_ID: yarrascrape
  _TARGET_DATASET: YarraPlanning
  _HERITAGE_PROPS_TABLE: YARRAHERITAGEMAPS_PROPERTIES

