steps:

# 1 REMOVE TABLE  _VHD_DETAILS
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_TARGET_DATASET}.${_VHD_DETAILS}'

# 2 CREATE TABLE: ${_VHD_DETAILS}
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'load'
  - '--project_id=${_PROJECT_ID}'
  - '--skip_leading_rows=1'
  - '--source_format=CSV'
  - '--path_to_source=_SOURCE_VHD_DETAILS_CSV'
  - '--replace=true'
  - '--autodetect=true'
  - '--destination_table=${_TARGET_DATASET}.${_VHD_DETAILS}'
  - |
    # TABLE - ${_VHD_DETAILS} - LOADED BY CLOUD BUILD build-tables.yaml
substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  _SRC_DATASET: YarraPlanning
  _TARGET_DATASET: PROD_DATASET

  # INPUTS TABLES
  _YARRA_OVERLAYS: YARRA_OVERLAYS
  _SOURCE_VHD_DETAILS_CSV: gs://yarra_planning_applications_au/yarra_vhr_20190802.csv
  
  # OUTPUTS
  _VHD_DETAILS: VHD_DETAILS
  
  # DECSCRIPTIONS
  _VHD_DETAILS_DESCR:  |
    TABLE - ${_VHD_DETAILS} - BUILT WITH CLOUD BUILD
    cloudbuild/build-tables.yaml. 
    LOADED FROM CSV FILE GENERATED BY SCRAPE_VHD


