steps:

# Remove HERITAGE_PROPS_VIEW
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_DATASET}.${_HERITAGE_PROPS_VIEW}'

# Create View HERITAGE_PROPS_VIEW from QUERY
# From tables 
#     HERITAGE_REGISTER_C191_WITHVHD
#    
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'mk'
  - '--use_legacy_sql=false'
  - '--project_id=${_PROJECT_ID}'
  - '--expiration=0'
  - '--description="Cloudbuild View of Overlays"'
  - |
    --view=
    # VIEW: HERITAGE_OVERLAY_WITH_ADDR_AND_PROPERTY
    # First Filter the Register to properties where PropertyId does not match any row in YARRA_PROPERTIES.
    # For those rows only, extract the PROP_PFI from the first matching YARRA_ADDRESS and use this to lookup a matching row in YARRA_PROPERTIES.
    # The output includes the matching PROPNUM, where one exists.
    # Where the second match fails, then matchingPROPNUM is null.
    # Outer filter takes the nulls from the matchingPROPNUM and tries to match on the second PFI in PROP_PFI array. This leaves only 68 non-matching addresses.
    WITH allmatches as (
    WITH firsmatchfailed as (
    WITH missingprops as (
    SELECT 
    r.* EXCEPT( Type,
        Number,
        Suburb,
        AddressName,
        number_last_suffix,
        state,
        postcode,
        number_first,
        street_type,
        number_last,
        locality_name,
        building_name,
        street_name,
        flat_number,
        number_first_suffix,
        flat_number_suffix),
    properties.LGA_CODE,
    properties.geom AS boundary1,
    properties.prop_pfi as prop_pfi1,
    properties.propnum as propnum1
    FROM`${_PROJECT_ID}.${_DATASET}.HERITAGE_REGISTER_C191_WITHVHD` r
    LEFT JOIN `${_PROJECT_ID}.${_DATASET}.YARRA_PROPERTIES` AS properties
    ON REGEXP_EXTRACT(r.PropertyId, r"[\d]*") = properties.PROPNUM
    )
    SELECT 
    properties.PROPNUM as propnum2,
    properties.prop_pfi as prop_pfi2,
    properties.geom as boundary2,
    missingprops.*
    from missingprops
    LEFT JOIN
      `${_PROJECT_ID}.${_DATASET}.YARRA_PROPERTIES` AS properties
    ON
      REGEXP_EXTRACT(missingprops.PROPERTY_PFI, r'\[\'(\d{3,12})\'.*\]') = CAST(properties.PROP_PFI AS STRING)
    )
    SELECT 
    REGEXP_EXTRACT(firsmatchfailed.PropertyId, r"[\d]*") as originalPROPNUM2,
    REGEXP_EXTRACT(PROPERTY_PFI, r'\[\'\d*\', \'\d*\', \'(\d{3,12})\'.*\]') as thirdPFI,
    properties.PROPNUM as propnum3,
    properties.prop_pfi as prop_pfi3,
    properties.geom as boundary3,
    firsmatchfailed.*
    from firsmatchfailed 
    LEFT JOIN
      `${_PROJECT_ID}.${_DATASET}.YARRA_PROPERTIES` AS properties
    ON 
      REGEXP_EXTRACT(firsmatchfailed.PROPERTY_PFI,  r'\[\'\d*\', \'\d*\', \'(\d{3,12})\'.*\]')  = CAST(properties.PROP_PFI AS STRING)
      )
    SELECT 
      IFNULL(boundary1, IFNULL(boundary2, boundary3)) as boundary,
      IFNULL(prop_pfi1, IFNULL(prop_pfi2, prop_pfi3)) as prop_pfi,
      IFNULL(propnum1, IFNULL(propnum2, propnum3)) as propnum,
      allmatches.* except(
      boundary1, boundary2, boundary3, 
      propnum1,propnum2, propnum3,
      prop_pfi1, prop_pfi2, prop_pfi3,
      originalPROPNUM2, thirdPFI)
    FROM allmatches
  - '${_DATASET}.${_HERITAGE_PROPS_VIEW}'

# Remove _OVERLAYS_AVG_DATE
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_DATASET}.${_OVERLAYS_AVG_DATE}'

# Create View _OVERLAYS_AVG_DATE from QUERY
# From tables 
#     YARRA_OVERLAYS
#     HERITAGEMAPS_PROPERTIES
#    
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'mk'
  - '--use_legacy_sql=false'
  - '--project_id=${_PROJECT_ID}'
  - '--expiration=0'
  - |
    --description=
    Cloudbuild VIEW
    Extract Details of the dates of all properties in each overlay
    Based on tables
      YARRAHERITAGEMAPS_PROPERTIES
      OVERLAY_SCHEDULE
  - |
    --view=
    #Cloudbuild VIEW
    #Extract Details of the dates of all properties in each overlay
    #Based on tables
    #  YARRAHERITAGEMAPS_PROPERTIES
    #  OVERLAY_SCHEDULE
    SELECT
    ovl.Overlay,
    HeritagePlace,
    CAST(FLOOR(AVG(earliest)) AS INT64)  as Avg_EstablishedDate,
    CAST(FLOOR(MIN(earliest)) AS INT64)  as Min_EstablishedDate,
    CAST(FLOOR(MAX(earliest)) AS INT64)  as Max_EstablishedDate
    FROM
      `_PROJECT_ID.${_DATASET}.YARRAHERITAGEMAPS_PROPERTIES` AS register
    LEFT JOIN
      `_PROJECT_ID.${_DATASET}.OVERLAY_SCHEDULE` AS ovl
    ON
      ovl.Overlay = register.Overlay
    WHERE
      earliest > 1800
    GROUP BY
      Overlay, HeritagePlace
  - '${_DATASET}.${_OVERLAYS_AVG_DATE}'

# Remove ${_OVERLAYS_VIEW}
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'rm'
  - '-f'
  - '-t'
  - '--project_id=${_PROJECT_ID}'
  - '${_DATASET}.${_OVERLAYS_VIEW}'

# Create View ${_OVERLAYS_VIEW} from QUERY
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: 
  - 'mk'
  - '--use_legacy_sql=false'
  - '--project_id=${_PROJECT_ID}'
  - '--expiration=0'
  - |
    --description=
    Cloudbuild VIEW
    Merge the Boundary Geometry from YARRA_OVERLAYS with the OVERLAY_SCHEDULE and OVERLAY_AVG_DATE
    Filter out not Yarra LGA overlays and no HO zone types
    Merge in the Average, Min and Max Established dates for each overlay.
    Based on tables
      OVERLAY_SCHEDULE
      YARRA_OVERLAYS
      OVERLAYS_AVG_ESTABLISHED_DATE
  - |
    --view=
    # Cloudbuild VIEW. See View Description
    WITH
      schedulewithboundary AS (
      SELECT
        * EXCEPT(geom,
          LGA_CODE,
          ZONESTATUS,
          PFI,
          ZONE_NUM,
          PFI_CR,
          UFI_CR,
          UFI),
        SAFE.ST_GeogFromGeoJson(geom) AS OverlayBoundary
      FROM
        `${_PROJECT_ID}.${_DATASET}.YARRA_OVERLAYS` AS zones
      LEFT JOIN
        `${_PROJECT_ID}.${_DATASET}.OVERLAY_SCHEDULE` AS schedule
      ON
        zones.ZONE_CODE= schedule.Overlay
      WHERE
        LGA='YARRA'
        AND SCHEMECODE='HO' )
    SELECT
      schedulewithboundary.*,
      dates.* EXCEPT(Overlay,
        HeritagePlace)
    FROM
      schedulewithboundary
    LEFT JOIN
      `${_PROJECT_ID}.${_DATASET}.OVERLAYS_AVG_ESTABLISHED_DATE` AS dates
    ON
      schedulewithboundary.ZONE_CODE = dates.Overlay
  - '${_DATASET}.${_OVERLAYS_VIEW}'

substitutions:
    _DATASET: YarraPlanning
    _PROJECT_ID: yarrascrape
    _HERITAGE_PROPS_VIEW: HERITAGE_OVERLAY_WITH_ADDR_AND_PROPERTY
    _OVERLAYS_AVG_DATE: OVERLAYS_AVG_ESTABLISHED_DATE
    _OVERLAYS_VIEW: OVERLAYS
