steps:

  # Don't get hung up on this just about running BigQuery commands.
  # Because you're working with containers here, you can run *anything*
  # you darn well please. It doesn't even have to be part of the GCP
  # ecosystem. Want to run some FORTRAN? Sure, go for it.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bq'
  args: ['mk', '--use_legacy_sql=false', '--view=SELECT 2', '--project_id=yarrascrape', '--expiration=0', '--description="Cloudbuild View of Overlays"', 'YarraPlanning.CloudTest']
