# This cloud build script is not working yet.
steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ '--prefix', 'yarraheritagemaps', 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ '--prefix', 'yarraheritagemaps', 'run', 'build', ' --prod']

  # Deploy to google cloud app egnine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['app', 'deploy',  'yarraheritagemaps/server/app.yaml', '--version=prod']

substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  