# This clodbuild config is not working.
steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ '--prefix', 'yarraheritagemaps', 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ '--prefix', 'yarraheritagemaps', 'run', 'build', ' --prod']

npm run 
substitutions:
  # PROJECT PARAMS
  _PROJECT_ID: yarrascrape
  